---
- name: Install docker
  gather_facts: No
  hosts: all
  vars:
    user_name: ansible
  tasks:
    - name: Install utils
      ansible.builtin.apt:
        name: "{{ item }}"
        state: latest

      with_items:
        # - yum-utils
        - gcc

    - name: move hello_world.c to /tmp
      copy:
        src: /root/demo/main.c
        dest: /tmp/main.c

    - name: compile and run simple hello world
      shell:
        cmd: |
          gcc /tmp/main.c -o /tmp/hello_world
          /tmp/hello_world

...